import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from app.config import SMTP_SERVER, SMTP_PORT, SMTP_USER, SMTP_PASSWORD, ALERT_SENDER
from app.logger import get_logger
from app.schemas import NotifyRequest, StudentAlert

logger = get_logger(__name__)


# ── Teacher summary email ─────────────────────────────────────────────────────

def _build_teacher_html(req: NotifyRequest) -> str:
    total_subjects = sum(len(s.subjects) for s in req.students)

    rows = ""
    for student in req.students:
        first = True
        for subj in student.subjects:
            pct = subj.attendance_percentage
            color = "#e74c3c" if pct < 65 else "#e67e22" if pct < 75 else "#27ae60"
            if first:
                rows += f"""
                <tr>
                    <td rowspan="{len(student.subjects)}" style="padding:10px 12px;border:1px solid #ddd;vertical-align:top;font-weight:600;">{student.name}</td>
                    <td rowspan="{len(student.subjects)}" style="padding:10px 12px;border:1px solid #ddd;vertical-align:top;">{student.usn}</td>
                    <td rowspan="{len(student.subjects)}" style="padding:10px 12px;border:1px solid #ddd;vertical-align:top;">{student.semester}</td>
                    <td style="padding:10px 12px;border:1px solid #ddd;">{subj.subject_name}</td>
                    <td style="padding:10px 12px;border:1px solid #ddd;text-align:center;font-weight:700;color:{color};">{pct}%</td>
                    <td style="padding:10px 12px;border:1px solid #ddd;text-align:center;">{subj.attended_classes}/{subj.total_classes}</td>
                </tr>"""
                first = False
            else:
                rows += f"""
                <tr>
                    <td style="padding:10px 12px;border:1px solid #ddd;">{subj.subject_name}</td>
                    <td style="padding:10px 12px;border:1px solid #ddd;text-align:center;font-weight:700;color:{color};">{pct}%</td>
                    <td style="padding:10px 12px;border:1px solid #ddd;text-align:center;">{subj.attended_classes}/{subj.total_classes}</td>
                </tr>"""

    return f"""
    <!DOCTYPE html>
    <html>
    <body style="font-family:Arial,sans-serif;background:#f4f4f4;padding:24px;">
      <div style="max-width:750px;margin:auto;background:#fff;border-radius:8px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.1);">

        <!-- Header -->
        <div style="background:#1a237e;padding:24px 32px;">
          <h2 style="color:#fff;margin:0;font-size:20px;">MSRIT — Attendance Alert</h2>
          <p style="color:#c5cae9;margin:6px 0 0;">Proctorship Notification System</p>
        </div>

        <!-- Body -->
        <div style="padding:28px 32px;">
          <p style="font-size:15px;color:#333;">Dear <strong>{req.teacher.name}</strong>,</p>
          <p style="font-size:14px;color:#555;line-height:1.6;">
            The following <strong>{len(req.students)} student(s)</strong> under your proctorship
            have <strong>{total_subjects} subject(s)</strong> with attendance below the required threshold.
            Please counsel them at the earliest.
          </p>

          <!-- Table -->
          <table style="width:100%;border-collapse:collapse;margin-top:16px;font-size:13px;">
            <thead>
              <tr style="background:#1a237e;color:#fff;">
                <th style="padding:10px 12px;text-align:left;border:1px solid #ddd;">Student Name</th>
                <th style="padding:10px 12px;text-align:left;border:1px solid #ddd;">USN</th>
                <th style="padding:10px 12px;text-align:left;border:1px solid #ddd;">Semester</th>
                <th style="padding:10px 12px;text-align:left;border:1px solid #ddd;">Subject</th>
                <th style="padding:10px 12px;text-align:center;border:1px solid #ddd;">Attendance %</th>
                <th style="padding:10px 12px;text-align:center;border:1px solid #ddd;">Attended/Total</th>
              </tr>
            </thead>
            <tbody>
              {rows}
            </tbody>
          </table>

          <p style="font-size:13px;color:#888;margin-top:24px;">
            This is an automated alert generated by the MSRIT Attendance Monitoring System.
            Please do not reply to this email.
          </p>
        </div>

        <!-- Footer -->
        <div style="background:#f0f0f0;padding:14px 32px;text-align:center;">
          <p style="font-size:12px;color:#999;margin:0;">
            RAMAIAH INSTITUTE OF TECHNOLOGY &nbsp;|&nbsp; Department of Computer Science &amp; Engineering
          </p>
        </div>

      </div>
    </body>
    </html>
    """


def send_email(req: NotifyRequest) -> tuple[bool, str]:
    """
    Build and send the HTML summary alert email to the teacher.
    Returns (success: bool, error_message: str).
    """
    subject = f"Attendance Alert — {len(req.students)} student(s) require attention"

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"]    = ALERT_SENDER
    msg["To"]      = req.teacher.email

    html_body = _build_teacher_html(req)
    msg.attach(MIMEText(html_body, "html"))

    try:
        with smtplib.SMTP(SMTP_SERVER, SMTP_PORT, timeout=15) as server:
            server.ehlo()
            server.starttls()
            server.ehlo()
            server.login(SMTP_USER, SMTP_PASSWORD)
            server.sendmail(ALERT_SENDER, req.teacher.email, msg.as_string())
        logger.info(f"Teacher email sent to {req.teacher.email} — {len(req.students)} students")
        return True, ""
    except smtplib.SMTPAuthenticationError:
        err = "SMTP authentication failed — check SMTP_USER and SMTP_PASSWORD (use Gmail App Password)"
        logger.error(err)
        return False, err
    except smtplib.SMTPException as e:
        err = f"SMTP error: {e}"
        logger.error(err)
        return False, err
    except Exception as e:
        err = f"Unexpected email error: {e}"
        logger.error(err)
        return False, err


# ── Student personalized email ────────────────────────────────────────────────

def _build_student_html(student: StudentAlert, teacher_name: str) -> str:
    rows = ""
    for subj in student.subjects:
        pct = subj.attendance_percentage
        color = "#e74c3c" if pct < 65 else "#e67e22" if pct < 75 else "#27ae60"
        rows += f"""
        <tr>
            <td style="padding:10px 12px;border:1px solid #ddd;">{subj.subject_name}</td>
            <td style="padding:10px 12px;border:1px solid #ddd;text-align:center;font-weight:700;color:{color};">{pct}%</td>
            <td style="padding:10px 12px;border:1px solid #ddd;text-align:center;">{subj.attended_classes}/{subj.total_classes}</td>
        </tr>"""

    return f"""
    <!DOCTYPE html>
    <html>
    <body style="font-family:Arial,sans-serif;background:#f4f4f4;padding:24px;">
      <div style="max-width:650px;margin:auto;background:#fff;border-radius:8px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.1);">

        <!-- Header -->
        <div style="background:#1a237e;padding:24px 32px;">
          <h2 style="color:#fff;margin:0;font-size:20px;">MSRIT — Attendance Warning</h2>
          <p style="color:#c5cae9;margin:6px 0 0;">Student Attendance Notification</p>
        </div>

        <!-- Body -->
        <div style="padding:28px 32px;">
          <p style="font-size:15px;color:#333;">Dear <strong>{student.name}</strong>,</p>
          <p style="font-size:14px;color:#555;line-height:1.6;">
            Your attendance in the following subject(s) has fallen below the required threshold.
            Please meet your proctor <strong>{teacher_name}</strong> at the earliest to discuss and
            regularise your attendance.
          </p>

          <table style="width:100%;border-collapse:collapse;margin-top:16px;font-size:13px;">
            <thead>
              <tr style="background:#1a237e;color:#fff;">
                <th style="padding:10px 12px;text-align:left;border:1px solid #ddd;">Subject</th>
                <th style="padding:10px 12px;text-align:center;border:1px solid #ddd;">Attendance %</th>
                <th style="padding:10px 12px;text-align:center;border:1px solid #ddd;">Attended / Total</th>
              </tr>
            </thead>
            <tbody>
              {rows}
            </tbody>
          </table>

          <p style="font-size:13px;color:#555;margin-top:20px;line-height:1.6;">
            <strong>USN:</strong> {student.usn} &nbsp;|&nbsp; <strong>Semester:</strong> {student.semester}
          </p>

          <p style="font-size:13px;color:#888;margin-top:16px;">
            This is an automated alert. Please do not reply to this email.
          </p>
        </div>

        <!-- Footer -->
        <div style="background:#f0f0f0;padding:14px 32px;text-align:center;">
          <p style="font-size:12px;color:#999;margin:0;">
            RAMAIAH INSTITUTE OF TECHNOLOGY &nbsp;|&nbsp; Department of Computer Science &amp; Engineering
          </p>
        </div>

      </div>
    </body>
    </html>
    """


def send_student_email(student: StudentAlert, teacher_name: str) -> tuple[bool, str]:
    """
    Send a personalized attendance warning email directly to the student.
    Returns (success: bool, error_message: str).
    Silently skips (returns False, reason) if student has no email address.
    """
    if not student.student_email:
        reason = f"No email on record for student {student.usn} — skipped"
        logger.info(reason)
        return False, reason

    subject = f"Attendance Warning — {len(student.subjects)} subject(s) below threshold | {student.usn}"

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"]    = ALERT_SENDER
    msg["To"]      = student.student_email

    html_body = _build_student_html(student, teacher_name)
    msg.attach(MIMEText(html_body, "html"))

    try:
        with smtplib.SMTP(SMTP_SERVER, SMTP_PORT, timeout=15) as server:
            server.ehlo()
            server.starttls()
            server.ehlo()
            server.login(SMTP_USER, SMTP_PASSWORD)
            server.sendmail(ALERT_SENDER, student.student_email, msg.as_string())
        logger.info(f"Student email sent to {student.student_email} ({student.usn})")
        return True, ""
    except smtplib.SMTPAuthenticationError:
        err = "SMTP authentication failed — check SMTP_USER and SMTP_PASSWORD"
        logger.error(err)
        return False, err
    except smtplib.SMTPException as e:
        err = f"SMTP error sending to {student.student_email}: {e}"
        logger.error(err)
        return False, err
    except Exception as e:
        err = f"Unexpected error sending to {student.student_email}: {e}"
        logger.error(err)
        return False, err
